seed = 37
data_dir = "data"
run_name = "rtx3090"

[preprocess]
L = 4
U = 1
dataset_size = 32
split = [0.8, 0.1, 0.1]

[train]
H = 8
batch_size = 64
epochs = 80
enc_w = 0.01
wm_w = 1.0
eval_w = 1.0

[test]
planner_samples = 32
test_limit = 0

[explore]
expert_steps = 12
planner_steps = 15
test_index = 0
